# Generated by Django 5.1.1 on 2024-10-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompID', models.CharField(max_length=20)),
                ('Did', models.CharField(max_length=20)),
                ('Comp', models.EmailField(max_length=254)),
                ('Btype', models.CharField(max_length=20)),
                ('Coll', models.DateField(max_length=20)),
                ('Exp', models.DateField(max_length=20)),
            ],
            options={
                'db_table': 'instock',
            },
        ),
    ]
