# Generated by Django 5.1.1 on 2024-10-03 20:38

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),  # Ensure this is correct.
    ]

    operations = [
        # If 'instock' model was not created in the initial migration, ensure it's created here
        migrations.CreateModel(
            name='InStock',
            fields=[
                ('CompID', models.AutoField(primary_key=True)),
                ('Did', models.CharField(max_length=20)),
                ('Comp', models.CharField(max_length=20)),
                ('Btype', models.CharField(max_length=20)),  # Add the 'Comp' field as needed
                ('Coll', models.DateField()),  # Adding/Modifying 'Coll' field to be DateField
                ('Exp', models.DateField()),   # Adding/Modifying 'Exp' field to be DateField
                # Add any other necessary fields here
            ],
        ),

        # Now, alter the fields as intended
        migrations.AlterField(
            model_name='instock',
            name='Coll',
            field=models.DateField(),  # Ensure 'Coll' is set to DateField
        ),
        migrations.AlterField(
            model_name='instock',
            name='Exp',
            field=models.DateField(),  # Ensure 'Exp' is set to DateField
        ),
    ]


