# Generated by Django 5.1.1 on 2024-10-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instock',
            name='Coll',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='instock',
            name='Comp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='instock',
            name='Exp',
            field=models.DateField(),
        ),
    ]
