# Generated by Django 5.1.1 on 2024-10-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_instock_coll_alter_instock_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instock',
            name='Comp',
            field=models.CharField(max_length=20),
        ),
    ]
