# Generated by Django 5.1.1 on 2024-10-04 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_instock_coll_alter_instock_comp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instock',
        ),
    ]
