# Generated by Django 5.1.1 on 2024-10-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_instock_comp'),
        ('dashboard', '0003_delete_instock'),
    ]

    operations = [
    ]
