# Generated by Django 5.1.1 on 2024-10-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_merge_0003_alter_instock_comp_0003_delete_instock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InStock',
        ),
    ]
