# Generated by Django 5.1.1 on 2024-10-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InStock',
            fields=[
                ('CompID', models.AutoField(primary_key=True)),
                ('Did', models.IntegerField()),
                ('Comp', models.CharField(max_length=100)),
                ('Btype', models.CharField(max_length=50)),
                ('Coll', models.CharField(max_length=50)),
                ('Exp', models.DateField()),
            ],
            options={
                'db_table': 'instock',
            },
        ),
    ]
