# Generated by Django 5.1.1 on 2024-10-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Used',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UcompID', models.CharField(max_length=20)),
                ('CompId', models.CharField(max_length=20)),
                ('Comp', models.CharField(max_length=20)),
                ('Btype', models.CharField(max_length=20)),
                ('Coll', models.DateField()),
                ('Exp', models.DateField()),
                ('Udate', models.DateField()),
            ],
            options={
                'db_table': 'used',
            },
        ),
    ]
