# Generated by Django 5.1.1 on 2024-10-05 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_used'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Used',
        ),
    ]
