# Generated by Django 5.1.1 on 2024-10-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_instock_id_alter_instock_btype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instock',
            name='CompID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
