# Generated by Django 5.1.1 on 2024-10-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_instock_btype_alter_instock_coll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instock',
            name='CompID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='instock',
            index=models.Index(fields=['Did'], name='instock_Did_cc0629_idx'),
        ),
    ]
