# Generated by Django 5.1.1 on 2024-10-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_instock_compid_instock_instock_did_cc0629_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instock',
            name='Coll',
            field=models.DateField(),
        ),
    ]
