# Generated by Django 5.1.1 on 2024-09-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UempId', models.CharField(max_length=20)),
                ('Uname', models.CharField(max_length=20)),
                ('Uemail', models.EmailField(max_length=254)),
                ('UjRole', models.CharField(max_length=20)),
                ('UidNum', models.CharField(max_length=20)),
                ('Upass', models.CharField(max_length=20)),
                ('UrPass', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
