# Generated by Django 5.1.1 on 2024-10-10 08:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='UDateJoined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='UPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
